
# File: .github/workflows/workflow.yml Azure web app deployment 

on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.ARM_AZURE_CREDENTIALS }}
    
    - run: |
        az webapp list --query "[?state=='Running']"

