
# File: .github/workflows/workflow.yml Azure web app deployment Testing on 12/8/2021 ran again on 1/11/2021

on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.ARM_AZURE_CREDENTIALS }}
    
    - run: |
        az webapp list --query "[?state=='Running']"
        terraform -version 
        #terraform init
        #terraform plan 
  
        


